@startuml C4_Context_Deposits
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

Person(Client, "Клиент", "Потенциальный/действующий клиент")
Person(CallCentreEmployee, "Оператор кол-центра", "Обрабатывает звонки")
Person(CreditOfficeEmployee, "Сотрудник отдела кредитования", "Работает со ставками")
Person_Ext(ExternalOperator, "Оператор партнёрского кол-центра", "Обрабатывает звонки")

System_Boundary(BankSystem, "Системы банка") {
    System(CallCentre, "Платформа кол‑центра", "CRM-система для обработки клиентских обращений")
    System(Catalog, "Сервис каталога", "Хранение и актуализация ставок/доступных депозитов")
}

System_Ext(ExternalSFTP, "Файловый сервер партнёрского кол-центра", "Хранение файлов с актуальными ставками")
System_Ext(ExternalCallCentre, "Платформа партнёрского кол-центра", "Внешняя CRM-система для обработки клиентских обращений")


'Actors rel
Rel(Client, CallCentreEmployee, "Совершает звонок")
Rel(Client, ExternalOperator, "Совершает звонок")
Rel(CreditOfficeEmployee, Catalog, "Обновляет ставки")
Rel(CallCentreEmployee, CallCentre, "Получает актуальные ставки")
Rel(ExternalOperator, ExternalCallCentre, "Получает актуальные ставки")

'Systems rel
Rel_L(Catalog, CallCentre, "Отправка актуальных ставок")
Rel(Catalog, ExternalSFTP, "Отправка актуальных ставок файлом")
Rel(ExternalSFTP, ExternalCallCentre, "Отправка актуальных ставок")

SHOW_LEGEND()
@enduml
